---
swagger: "2.0"
info:
  description: "AllCare API"
  version: "1.0.0"
  title: "AllCare API"
  contact:
    email: "prakashp@ezeees.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/RiseCorp/AllCare/1.0.0"
schemes:
- "https"
- "http"
paths:
  /getUserDetails:
    post:
      summary: "get user details while unified login"
      description: "To get user practice id, practice url, and username from user\
        \ selected object type and email address"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "getUserDetails"
        description: "To get user practice id, practice url, and username from user\
          \ selected object type and email address"
        required: true
        schema:
          $ref: "#/definitions/getUserDetails"
      responses:
        200:
          description: "success"
          schema:
            type: "object"
            properties: {}
        204:
          description: "No data available."
        400:
          description: "(Bad Request or validation errors or exception errors)."
        401:
          description: "Unauthorized request."
      security:
      - apikey: null
securityDefinitions:
  BasicAuth:
    type: "basic"
  ApiKey:
    type: "apiKey"
    name: "apikey"
    in: "header"
definitions:
  getUserDetails:
    type: "object"
    required:
    - "email"
    - "objecttype"
    properties:
      objecttype:
        type: "string"
        format: "alpha"
        description: "object type"
        enum:
        - "practice"
        - "patient"
        - "agency"
      email:
        type: "string"
        format: "email"
  practicesList:
    type: "object"
    required:
    - "data"
    - "message"
    - "status_code"
    properties:
      status_code:
        type: "integer"
        description: "response code from service"
      message:
        type: "string"
        description: "response message from service"
      data:
        type: "object"
        description: "response data from service"
        properties: {}
x-apigee-id: "AllCareCentralQA01"
